// <auto-generated />
using System;
using BackUserTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackUserTest.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230316060832_v1.1")]
    partial class v11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackUserTest.Models.Persona", b =>
                {
                    b.Property<int>("idPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("numero_identificacion")
                        .HasColumnType("int");

                    b.Property<string>("tipo_identificacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idPersona");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BackUserTest.Models.Usuario", b =>
                {
                    b.HasBaseType("BackUserTest.Models.Persona");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
